apiVersion: v1
kind: Namespace
metadata:
  name: test-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: test-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
      - name: api-con
        image: scinet0786/api-con
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: test-api
spec:
  selector:
    app: api-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
